/**
 * Generated by GenAttributeDemoManifestPlugin — do not edit.
 */
export const GEN_ATTRIBUTE_BUNDLED_DEMO_SLUGS: readonly string[] = ["CN->EN翻译","Write a sonnet about love","写一首绝句，主题是春天","过拟合｜李白 将进酒"];
