/**
 * 构建前扫描 `assets/demos/causal_flow/*.json`，写入 `features/causal_flow/genAttributeBundledDemoManifest.generated.ts`，供 bundle 内联 demo 列表。
 * 顺序与 UI 名：`order.json` 数组；项为 slug 字符串或 `{ slug, label? }`（无 label 则 UI 显示 slug）。
 * 未列入 order 的 demo 按 UTF-16 码元序追加到末尾，label 同 slug。
 * order 中的 slug 必须对应目录内已有 demo JSON；重复 slug 亦会在构建时报错。
 */
const path = require('path');
const fs = require('fs');

const REL_DIR = 'assets/demos/causal_flow';
const GENERATED_BASENAME = 'genAttributeBundledDemoManifest.generated.ts';
const ORDER_FILENAME = 'order.json';

function utf16Sort(slugs) {
    return [...slugs].sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
}

function discoverSlugs(srcDir) {
    if (!fs.existsSync(srcDir)) return [];
    return fs
        .readdirSync(srcDir)
        .filter((f) => f.endsWith('.json') && f !== ORDER_FILENAME)
        .map((f) => f.replace(/\.json$/i, ''))
        .filter((s) => s.length > 0);
}

/** @returns {{ slug: string, label: string | null } | null} */
function parseOrderEntry(entry, index) {
    const at = `${ORDER_FILENAME}[${index}]`;
    if (typeof entry === 'string') {
        const slug = entry.trim();
        return slug ? { slug, label: null } : null;
    }
    if (entry && typeof entry === 'object' && typeof entry.slug === 'string') {
        const slug = entry.slug.trim();
        if (!slug) return null;
        const label =
            typeof entry.label === 'string' && entry.label.trim().length > 0
                ? entry.label.trim()
                : null;
        return { slug, label };
    }
    throw new Error(
        `${at}: expected a slug string or { "slug": "...", "label"?: "..." }`
    );
}

function readOrderEntries(srcDir) {
    const orderPath = path.join(srcDir, ORDER_FILENAME);
    if (!fs.existsSync(orderPath)) return null;
    let raw;
    try {
        raw = JSON.parse(fs.readFileSync(orderPath, 'utf8'));
    } catch (e) {
        throw new Error(`${ORDER_FILENAME}: invalid JSON (${e.message})`);
    }
    if (!Array.isArray(raw)) {
        throw new Error(`${ORDER_FILENAME}: expected a JSON array`);
    }
    return raw.map((entry, i) => parseOrderEntry(entry, i)).filter(Boolean);
}

function resolveLabel(slug, label) {
    return label ?? slug;
}

function collectDemoEntries(srcDir) {
    const discovered = new Set(discoverSlugs(srcDir));
    const order = readOrderEntries(srcDir);
    if (order == null) {
        return utf16Sort([...discovered]).map((slug) => ({
            slug,
            label: slug,
        }));
    }
    const seen = new Set();
    const result = [];
    for (const { slug, label } of order) {
        if (seen.has(slug)) {
            throw new Error(`${ORDER_FILENAME}: duplicate slug ${JSON.stringify(slug)}`);
        }
        if (!discovered.has(slug)) {
            throw new Error(
                `${ORDER_FILENAME}: unknown slug ${JSON.stringify(slug)} (no ${slug}.json under ${REL_DIR})`,
            );
        }
        seen.add(slug);
        result.push({ slug, label: resolveLabel(slug, label) });
    }
    for (const slug of utf16Sort([...discovered].filter((s) => !seen.has(s)))) {
        result.push({ slug, label: slug });
    }
    return result;
}

function writeGeneratedModule(srcDir, outPath) {
    const entries = collectDemoEntries(srcDir);
    const content =
        '/**\n' +
        ' * Generated by GenAttributeDemoManifestPlugin — do not edit.\n' +
        ' */\n' +
        'export type GenAttributeBundledDemoManifestEntry = { readonly slug: string; readonly label: string };\n' +
        `export const GEN_ATTRIBUTE_BUNDLED_DEMOS: readonly GenAttributeBundledDemoManifestEntry[] = ${JSON.stringify(entries)};\n`;
    if (fs.existsSync(outPath) && fs.readFileSync(outPath, 'utf8') === content) return;
    fs.mkdirSync(path.dirname(outPath), { recursive: true });
    fs.writeFileSync(outPath, content, 'utf8');
}

class GenAttributeDemoManifestPlugin {
    apply(compiler) {
        const srcDir = path.join(__dirname, '..', REL_DIR);
        const outPath = path.join(__dirname, '..', 'features', 'causal_flow', GENERATED_BASENAME);

        compiler.hooks.beforeCompile.tapAsync('GenAttributeDemoManifestPlugin', (_params, callback) => {
            try {
                writeGeneratedModule(srcDir, outPath);
                callback();
            } catch (e) {
                callback(e);
            }
        });

        compiler.hooks.thisCompilation.tap('GenAttributeDemoManifestPlugin', (compilation) => {
            compilation.contextDependencies.add(srcDir);
        });
    }
}

module.exports = { GenAttributeDemoManifestPlugin };
