/**
 * Generated by GenAttributeDemoManifestPlugin — do not edit.
 */
export type GenAttributeBundledDemoFeaturedStyle = 'bold';
export type GenAttributeBundledDemoManifestEntry = { readonly slug: string; readonly label: string; readonly featured?: GenAttributeBundledDemoFeaturedStyle };
export const GEN_ATTRIBUTE_BUNDLED_DEMOS: readonly GenAttributeBundledDemoManifestEntry[] = [{"slug":"Write a sonnet about love","label":"Poem | Write a sonnet about love","featured":"bold"},{"slug":"写一首绝句，主题是春天","label":"写诗 | 写一首绝句，主题是春天","featured":"bold"},{"slug":"CoT｜苏州所在省的省会","label":"CoT | 苏州所在省的省会","featured":"bold"},{"slug":"CoT｜苏州所在省的省会城市里最高的山","label":"CoT | 苏州所在省的省会的最高的山"},{"slug":"CoT｜反向传播归因动画","label":"CoT | 思维链的反向传播归因动画","featured":"bold"},{"slug":"CoT｜最长两条河的入海口｜草稿链","label":"CoT | 最长两条河的入海口｜草稿链","featured":"bold"},{"slug":"CoT｜多“跳”推理","label":"CoT | 多跳推理中“跳”的具象化"},{"slug":"strawberry里有几个r","label":"CoT | strawberry里有几个r"},{"slug":"ReAct｜Tool-call｜北京天气","label":"ReAct｜Tool-call｜北京天气","featured":"bold"},{"slug":"过拟合｜李白 将进酒","label":"过拟合｜李白 将进酒","featured":"bold"},{"slug":"CN-EN翻译","label":"CN->EN | 翻译"}];
