/**
 * Generated by GenAttributeDemoManifestPlugin — do not edit.
 */
export type GenAttributeBundledDemoManifestEntry = { readonly slug: string; readonly label: string };
export const GEN_ATTRIBUTE_BUNDLED_DEMOS: readonly GenAttributeBundledDemoManifestEntry[] = [{"slug":"Write a sonnet about love","label":"Poem | Write a sonnet about love"},{"slug":"写一首绝句，主题是春天","label":"写诗 | 写一首绝句，主题是春天"},{"slug":"CoT | 苏州所在省的省会","label":"CoT | 苏州所在省的省会"},{"slug":"CoT | 多“跳”推理","label":"CoT | 多“跳”推理"},{"slug":"过拟合｜李白 将进酒","label":"过拟合｜李白 将进酒"},{"slug":"CN->EN翻译","label":"CN->EN | 翻译"}];
